
insert into Users (Username, passwords, email)
values 
('S2jriStS7mKdRhjHJt0V','iYroVq3hGyZYXBeKf0mKQv','gS4VltlQIZPe9xgDmeHB@gmail.com'),
('JFEkVD2HG0XBeKf0mKQv','tqZXFmVuiroQKQYqK9g','9DsF26Up1E1D4V@sis.hust.edu.vn'),
('KQYqK9gSjpUhuEBBIlFg','G315g0BDKmvgonGBjFqrnks','Phbafx8FlNjNbk@yahoo.com'),
('UnonGBjFqrnks7EdpEDq','HONW9KFZ53VpRNwULKVh','eOAomn6w7pAJp8pax@gmail.com'),
('RNwULKVhTDaJ9xWeARtb','Kf6LFKymHK5DDDGEZWpZS','pSBPhDXI0xwE4CP@gmail.com'),
('YWDDGEZWpZSX0vpMugEh','ZKA1u0ZMrDF2A0WS4Vf7fL','ObjKNzJrglzSZ@gmail.com'),
('sEgkeA0WS4Vf7fLHMSGg','bNLK3YiKxQyyqzzqpadyay','HUL24UyYbCeNdiNz@yahoo.com'),
('YRRj5vQsAqzzqpadyayz','pq1fkj6UnTWcBGmaZZp','MaTJLO5xWFrVcK1b@gmail.com'),
('xtUKIZQ82wAsBGmaZZpY','mZC25fm3WzuwNZupdo1c','SgJ9IN8Xw5JGX6gW@gmail.com'),
('8YQHCe9ILrSlPC6aWj1E','tmcKRoTzydaAo1cHTFkY','QL3GkkmwRSCmSu67@yahoo.com'),
('1TSfNZupdo1cHTFkYYw8','J1PeA0lgYTs4mmWV5a9','oxs7iYyf3WCPgnr@gmail.com'),
('k33OVvZuNUmmWV5a9G76','muuBKf0KwrYJ4KtsvAG','gVoWNxJCTCcfDyO@yahoo.com'),
('BZL6CMSW6MZHA4KtsvAG','RuKNj3QVQ2wbQP3DUIz1','nZRNwyqQ9rh375Hkm@yahoo.com'),
('NN2qJEEutOQP3DUIz1KS','xKrwapugfAFNUBnLdUZmeo7a','nXEExC80qT6TXmYPCF@yahoo.com'),
('FwJlpufUBnLdUZmeo7a7','CyjzPwjgVLYFNN2qJEEutOQP3DUIz1KS','iiE5EMe2uu0SMGXsCWK@gmail.com'),
('gLwiqPd0Zzc7jQnNHbrM','jTCPnU6FqHsWfPPn3cf6T','BqyB6T5aroIaT@yahoo.com'),
('n9Jl7OofPPn3cf6TAym4','b4FvSWoYeyDmVsWu6JQr','8tzCRzpIl75ZXONLOJ@gmail.com'),
('Qa2gGVsWu6JQrneUxYvo','xafYUjRIv1EYmQLK4STXcgSA','8OR2cOC05hbcXX@yahoo.com'),
('5smAmQLK4STXcgSAhFi1','xNRxTjPVUdoQOkyVSrLXjPR3b','pyK8Ze8uoxwJeLnc@sis.hust.edu.vn'),
('HOkyVSrLXjPR3b4isiwc','fJUffwmdNHAEVSrLXjPR3b4isiw','VLDw3NRb6chVS5lY@sis.hust.edu.vn')



insert into Body_index(name, age, sex, height, weight,TDEE)
values
('Bui Dieu linh','65','F','197','68',''),
('Chi Van Linh','60','F','134','48',''),
('Ly Thuan Nam','38','M','170','108',''),
('Do Van Son','58','M','187','104',''),
('Thanh Dat','88','M','164','58',''),
('Nguyen Hoai Linh','96','F','130','63',''),
('Nguyen Dieu Anh','52','F','185','120',''),
('Bui Tien Thanh','62','M','170','70',''),
('Pham Thu Trang','39','F','178','105',''),
('Tran Lyn Lyn','16','F','161','60',''),
('Tran Minh Ngoc','67','F','153','48',''),
('Nguyen Thu Giang','29','F','158','54',''),
('Vu Viet Bach','46','M','149','60',''),
('Dong Gang Thep','30','M','157','60',''),
('Nguyen Quoc Anh','11','M','156','41',''),
('Bui Thao Nhi','69','F','164','90',''),
('Bui Hoang Khanh','65','M','140','47',''),
('Tran Hoang Anh','91','F','146','35',''),
('Nguyen Xuan Mai','20','F','150','44',''),
('Nguyen Hoang','76','M','200','110','')

insert into Food_list (Food, Calories)
values    
('APPLE, RAW, WITH SKIN','52'),
('APPLE, RAW, WITHOUT SKIN','48'),
('ASPARAGUS,RAW','20'),
('AVOCADOS,RAW,ALL COMM VAR','160'),
('BANANA, RAW','89'),
('BEEF,SHRT LOIN,PRTRHS STEAK,LN,1/8" FAT,CHOIC,RAW','161'),
('BEEF,SHRT LOIN,T-BONE STEAK,BONE-IN,LN,1/8" FAT,CHOIC,RAW','160'),
('BEVERAGES,ALMOND MILK,CHOC,RTD','50'),
('BEVERAGES,COFFEE,BREWED,BRKFST BLEND','2'),
('BEVERAGES,COFFEE,BREWED,ESPRESSO,REST-PREP,DECAFFEINATED','9'),
('BEVERAGES,COFFEE,READY TO DRK,VANILLA,LT,MILK BSD,SWTND','36'),
('BLUEBERRIES, RAW','57'),
('BREADFRUIT,RAW','103'),
('BROCCOLI,CHINESE,RAW','30'),
('CANDIES,CARAMELS','382'),
('CARROTS,RAW','41'),
('CEREALS,QUAKER,INST OATMEAL,BANANA BREAD,DRY','368'),
('CHEESE,BLUE','353'),
('CHEESE,CHEDDAR','404'),
('CHIA SEEDS,DRIED','486'),
('CHICKEN,BROILER,ROTISSERIE,BBQ,BREAST MEAT ONLY','144'),
('CHICKEN,BROILERS OR FRYERS,MEAT & SKN,RAW','215'),
('CHICKEN,BROILERS OR FRYERS,MEAT&SKN,CKD,FRIED,BATTER','289'),
('CROISSANTS,BUTTER','406'),
('CUCUMBER,PEELED,RAW','12'),
('CUCUMBER,WITH PEEL,RAW','15'),
('DESSERTS,FLAN,CARAMEL CUSTARD,PREPARED-FROM-RECIPE','145'),
('EGG,WHITE,RAW,FRESH','52'),
('EGG,YOLK,RAW,FRSH','322'),
('FAST FOODS, POTATO, FRNCH FRIED IN VEG OIL','312'),
('FISH BROTH','16'),
('FISH,SALMON,PINK,CND,TOTAL CAN CONTENTS','129'),
('FRUIT SALAD,CND,HVY SYRUP,SOL&LIQUIDS','73'),
('GRAPEFRUIT,RAW,PINK&RED&WHITE,ALL AREAS ','32'),
('HAM SALAD SPREAD','216'),
('ICE CRM BAR,COVERED W/ CHOC & NUTS','303'),
('ICE CRM SANDWCH','237'),
('ICE CRM,LOWFAT,NO SUGAR ADDED,CONE,ADDED PNUTS & CHOC SAU','265'),
('ICE CRM,SOFT SERVE,CHOC','222'),
('KELLOGGS,POP-TARTS,YUM-AZING VANILLA MILKSHAKE TOASTER PAST','398'),
('LEMON JUICE,RAW','22'),
('LEMONS,RAW,WITHOUT PEEL','29'),
('MANGOS,RAW','60'),
('MILK SHAKES,THICK VANILLA','112'),
('MILK,FLUID,NONFAT,CA FORT (FAT FREE OR SKIM)','35'),
('MONKFISH,RAW','76'),
('MUSHROOMS,BROWN,ITALIAN,OR CRIMINI,EXPOSED TO UV LT,RAW','22'),
('MUSHROOMS,WHITE,CKD,BLD,DRND,W/ SALT','28'),
('NUTMEG,GROUND','525'),
('ORANGE JUICE, RAW',''),
('PEANUTS,ALL TYPES,RAW',''),
('PICKLES,CUCUMBER,SWT (INCLUDES BREAD & BUTTER PICKLES)',''),
('PINEAPPLE, RAW',''),
('POPCORN,CARAMEL-COATED,W/PNUTS',''),
('POPCORN,CARAMEL-COATED,WO/PNUTS',''),
('PREGO PASTA,TOMATO,BASIL & GARLIC ITAL SAU,RTS',''),
('PUDDINGS,BANANA,DRY MIX,INST',''),
('RICE NCKDOODLES,',''),
('RICE,WHITE,LONG-GRAIN,PARBLD,UNENR,DRY',''),
('SALMON,ATLANTIC,WILD,RAW',''),
('SANDWICH SPREAD,PORK,BEEF',''),
('SEAWEED,AGAR,RAW',''),
('SOUP,BLACK BEAN',''),
('SOUP,CHICK,CND,CHUNKY,RTS',''),
('SPINACH,RAW',''),
('SWEET POTATO,FRZ,UNPREP',''),
('TOFU,FRIED',''),
('TOMATOES,GREEN,RAW',''),
('TOMATOES,RED,RIPE,RAW,YEAR RND AVERAGE',''),
('TOMATOES,YELLOW,RAW',''),
('TUNA,FRESH,BLUEFIN,RAW',''),
('WATERMELON,RAW',''),
('YOGURT,CHOC,NONFAT MILK',''),
('YOGURT,GREEK,PLN,NONFAT',''),
('YOGURT,GREEK,STRAWBERRY,DANNON OIKOS',''),