use weight_tracker

INSERT INTO Activity_list( [Activity_name] , [Calories] )
VaLUES
( 'Aerobic dancing (high impact) ', '7 '),
( 'Aerobic dancing (low impact) ', '5 '),
( 'Baseball/softball ', ' 5'),
( ' Basketball', '6 '),
( 'Beach volleyball ', ' 8'),
( 'Bowling ', '3 '),
( 'Boxing ', '6 '),
( 'Canoeing/rowing', '7'),
( 'Cycling', '8'),
( 'Football', '8'),
( 'Golf', '5'),
( 'Gymnastics', '4'),
( 'Hiking' , '6'),
( 'Horseback riding', '4'),
( 'Ice hockey', '8'),
( 'Jumping rope', '11'),
( 'Kayaking', '5'),
( ' Martial arts', '11'),
( 'Pilates', '3'),
( 'Rock climbing', '8 '),
( 'Roller skating', '7'),
( 'Rugby', '11'),
( 'Running', '11'),
( 'Sailing', '3'),
( 'Scuba diving/Freediving', '7'),
( 'Skateboarding', '5'),
( 'Skiing', '7'),
( 'Soccer', '7'),
( 'Sleeping', '1'),
( 'Climbing stairs ', '9 '),
( 'Stretching', '3'),
( 'Surfing', '3'),
( 'Swimming', '8'),
( ' Table tennis', '4'),
( 'Tai chi ', '4'),
( 'Tennis', '7'),
( 'Volleyball', '4'),
( 'Walking', '3'),
( 'Wrestling', '6'),
( 'Yoga', '3')
